name: Generar Snake Game

on:
  push:           
    branches:
      - main       
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Generar animación del Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          output_dir: dist
          palette: github-dark # Opcional: Puedes especificar la paleta de colores

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Añadir SVG al repositorio
        run: |
          git add dist/github-snake.svg
          git add dist/github-snake-dark.svg
          git commit -m "Actualizar animación del Snake Game [skip ci]" || echo "No changes to commit"

      - name: Push cambios
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Publicar artefactos
        uses: actions/upload-artifact@v3
        with:
          name: snake-game
          path: dist/
