name: Generar Snake Game

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Generar animación del Snake Game en SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
          squares_only: false
          color_snake: orange

      - name: Configurar Git y Push Cambios
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: main
          build_dir: dist
          commit_message: "Actualizar animación del Snake Game en SVG [skip ci]"
          force_orphan: true
          keep_history: false

      - name: Publicar artefactos
        uses: actions/upload-artifact@v4
        with:
          name: snake-game-svgs
          path: dist/
          retention-days: 5