name: Generar Snake Game

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Crear directorio dist si no existe
        run: mkdir -p dist

      - name: Generar animación del Snake Game en SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Verificar archivos generados
        run: |
          echo "Archivos generados en el directorio dist:"
          ls -la dist

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Añadir SVGs al repositorio
        run: |
          git add dist/github-snake.svg || echo "Archivo github-snake.svg no encontrado"
          git add dist/github-snake-dark.svg || echo "Archivo github-snake-dark.svg no encontrado"
          git commit -m "Actualizar animación del Snake Game en SVG [skip ci]" || echo "No hay cambios para confirmar"

      - name: Push cambios
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Publicar artefactos
        uses: actions/upload-artifact@v4
        with:
          name: snake-game-svgs
          path: dist/
